version: "3.8"

services:

  db:
    container_name: mysql_db
    image: mysql
    restart: always
    ports:
      - 4306:4306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: app
    build: .
    command: uvicorn backend.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:

    null
